### ISSUE TITLE
为什么调用js接口的时候需要传signData 

### ISSUE THREAD

**Issue by wyfj2001** [liuxiaodong/wechat-iot-example#1]
为什么调用js接口的时候需要传signData 

signData = {
      "verifyAppId": data.appid,
      "verifyTimestamp": data.timestamp,
      "verifySignType": "sha1",
      "verifyNonceStr": data.nonceStr,
      "verifySignature": data.signature
    };

或
mixin(//other, signData)

不传的话有什么问题么？

**Comment by liuxiaodong** [comment]
早期微信的文档需要这么传，现在应该可以不传这些参数了。
