### ISSUE TITLE
创建菜单失败

### ISSUE THREAD

**Issue by gyb510** [liuxiaodong/wechat-iot-example#2]
我是做嵌入式的，服务器小白，手里有sensortag的开发套件，按步骤配置测试公众号，出现菜单创建失败问题，看原因是id和secret都没有获取到，不知道怎么改，除了菜单创建失败，公众号可以访问了，谢谢
weixin server listening on port 3000
创建菜单失败: {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","name":"WeChatAPIRequestError","path":"/?grant_type=client_credential&appid=undefined&secret=undefined","status":-1,"headers":{},"res":{"status":-1,"statusCode":-1,"headers":{},"size":0,"aborted":false,"rt":9,"keepAliveSocket":false,"requestUrls":["http://undefinedtoken?grant_type=client_credential&appid=undefined&secret=undefined"]}}

**Comment by liuxiaodong** [comment]
😯   ， 这是由于其中一个依赖有一个不兼容的升级导致的。我现在已经更新了。你再 pull 一下最新的代码并 npm install 后应该就 OK 了

**Comment by gyb510** [comment]
谢谢了，大神
