### ISSUE TITLE
js报错

### ISSUE THREAD

**Issue by Jeijie** [liuxiaodong/wechat-iot-example#3]
vue.min.js:1 Uncaught SyntaxError: Unexpected token <
jquery.min.js:1 Uncaught SyntaxError: Unexpected token <
base64.min.js:1 Uncaught SyntaxError: Unexpected token <
drag.js:2 Uncaught ReferenceError: Vue is not defined(anonymous function) @ drag.js:2(anonymous function) @ drag.js:81
iot.js:28 Uncaught ReferenceError: $ is not defined

**Comment by liuxiaodong** [comment]
你安装依赖了吗？
